# Generated by Django 6.0.3 on 2026-06-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='lenght',
            new_name='length',
        ),
    ]
